# Generated by Django 3.1.1 on 2020-09-11 12:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('feedlink', models.CharField(max_length=200, unique=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('link', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='live_feed.source')),
            ],
            options={
                'unique_together': {('guid', 'source')},
            },
        ),
    ]
