# Generated by Django 3.1.1 on 2020-11-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_feed', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='classified',
            field=models.BooleanField(default=False),
        ),
    ]
