# Generated by Django 3.0.8 on 2020-07-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.TextField()),
                ('url', models.URLField()),
                ('time', models.DateTimeField()),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Disaster_type',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
