# Generated by Django 3.0.8 on 2020-07-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0003_auto_20200704_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
