# Generated by Django 3.0.8 on 2020-10-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0004_auto_20200705_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='label1',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='label2',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='label3',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
    ]
