# Generated by Django 3.0.8 on 2020-11-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0006_auto_20201102_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='label1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='label2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='label3',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
