# Generated by Django 3.0.8 on 2020-11-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0007_auto_20201102_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='label1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='label2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='label3',
        ),
    ]
