# Generated by Django 3.1.1 on 2020-11-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0009_auto_20201126_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='label1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='label2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='label3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='label',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
