# Generated by Django 3.1.1 on 2020-12-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0011_auto_20201130_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
